#!/usr/bin/make -f

include ../scripts/check.mk

PACKER ?= packer
PACKER_LOG ?= 0
TIMEOUT ?= 1h
ARCH ?= x86_64

# bootc-specific variables
BOOTC_IMAGE_REF ?= $(error BOOTC_IMAGE_REF is required - e.g., registry:example.com/org/rocky10-bootc:latest)
BOOTC_REGISTRY_URL ?=
BOOTC_REGISTRY_AUTH ?=
BOOTC_REGISTRY_INSECURE ?= false

# Detect if running on ARM host
ifeq ($(shell uname -m),aarch64)
    HOST_IS_ARM = true
else
    HOST_IS_ARM = false
endif

ifeq ($(wildcard /usr/share/OVMF/OVMF_CODE.fd),)
	OVMF_SFX ?= _4M
else
	OVMF_SFX ?=
endif

export PACKER_LOG

# Fallback
ifeq ($(strip $(ARCH)),amd64)
	ARCH = x86_64
endif

.PHONY: all clean lint format

all: rocky10-bootc.tar.gz

$(eval $(call check_packages_deps))

lint:
	packer validate \
		-var bootc_image_ref="registry:example.com/test:latest" \
		rocky10-bootc.pkr.hcl
	packer fmt -check -diff .

format:
	packer fmt .

OVMF_VARS.fd: /usr/share/OVMF/OVMF_VARS${OVMF_SFX}.fd
	cp -v $< ${ARCH}_VARS.fd

SIZE_VARS.fd:
ifeq ($(strip $(ARCH)),aarch64)
	truncate -s 64m ${ARCH}_VARS.fd
else
	truncate -s 2m ${ARCH}_VARS.fd
endif

rocky10-bootc.tar.gz: check-deps clean OVMF_VARS.fd SIZE_VARS.fd
	${PACKER} init rocky10-bootc.pkr.hcl && ${PACKER} build \
		-var architecture=${ARCH} \
		-var host_is_arm=${HOST_IS_ARM} \
		-var timeout=${TIMEOUT} \
		-var ovmf_suffix=${OVMF_SFX} \
		-var bootc_image_ref=${BOOTC_IMAGE_REF} \
		$(if $(BOOTC_REGISTRY_URL),-var bootc_registry_url=${BOOTC_REGISTRY_URL}) \
		$(if $(BOOTC_REGISTRY_AUTH),-var bootc_registry_auth=${BOOTC_REGISTRY_AUTH}) \
		-var bootc_registry_insecure=${BOOTC_REGISTRY_INSECURE} \
		rocky10-bootc.pkr.hcl

clean:
	${RM} -rf *.fd output-rocky10-bootc rocky10-bootc.tar.gz
